cts2/lexevs-service

- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/BasicEntityDirectoryBuilder.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/SearchExtensionEntityQueryService.java
Fix for issue LEXEVS-1797 to align with new LexEVS SearchExtension changes.
> Fix for issue LEXEVS-1797 to align with new LexEVS SearchExtension changes.

- pom.xml
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/resolvedvalueset/LexEvsResolvedValueSetResolutionService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/transform/TransformUtils.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/uri/RestUriResolver.java
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/EntityUriResolverTestIT.java
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/LexEvsEntityQueryServiceIntegrationTestIT.java
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/uri/RestUriResolverTest.java
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/uri/TestRestUriResolver.java
- src/test/resources/lexevs/test-content/Automobiles.xml
- src/test/resources/test-lexevs-context.xml
Pulling in LEXEVSCTS2-53 (colon parsing fix) 
Pulling in LEXEVSCTS2-45 - (Java 8 fix)
Updating pom file to include 6.4.1 lexevs artifacts.
> Pulling in colon parsing changes and Java 8 fix from dev branch and updating pom for 6.4.1

- pom.xml
Pull request to update dev branch with contents of v1.5.0 branch contents.
> Updating dev with v1.5.0 branch

- pom.xml
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/resolvedvalueset/LexEvsResolvedValueSetResolutionService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/transform/TransformUtils.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/uri/RestUriResolver.java
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/EntityUriResolverTestIT.java
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/LexEvsEntityQueryServiceIntegrationTestIT.java
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/uri/RestUriResolverTest.java
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/uri/TestRestUriResolver.java
- src/test/resources/lexevs/test-content/Automobiles.xml
- src/test/resources/test-lexevs-context.xml
Pull request to update master branch with contents of v1.5.0 branch contents.
> Updating master with v1.5.0 branch

- README.md
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/LexBigServiceFactory.java
- src/main/resources/OSGI-INF/metatype/metatype.xml
- src/test/resources/lexevs-service.properties
LEXEVSCTS2-61 Removed useRemoteAPI option from lexevs-services.properties and associated code.
> LEXEVSCTS2-61 - Removed useRemoteAPI option from lexevs-services.properties and associated code.

- pom.xml
Updated maven pom.xml to pull artifacts from the NCI Nexus Server.
> LEXEVSCTS2-74 Updated pom file to point to NCI's Nexus server

- pom.xml
LEXEVSCTS2-94 Updated the lexevs-service version to 1.5.1.2 and lexevs-version to 6.4.1.2
> LEXEVSCTS2-94 Updated the lexevs-service version to 1.5.1.2 and lexevs-version to 6.4.1.2

- pom.xml
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/bulk/codesystemversion/SearchExtensionBulkDownloader.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/bulk/mapversion/MappingExtensionBulkDownloader.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/LexEvsEntityQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/mapentry/LexEvsMapEntryReadService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/resolvedvalueset/LexEvsResolvedValueSetResolutionService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/valuesetdefinition/LexEvsValueSetDefinitionResolutionService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/utility/CommonUtils.java
Bugfix/lexevscts2 132 Merge v1.5.2 branch to dev branch.
> Bugfix/lexevscts2 132 Merge v1.5.2 branch to dev branch.

- pom.xml
LEXEVSCTS2-145 Update pom file to update the lexevs version to 6.5.0.SNAPSHOT.1
> LEXEVSCTS2-145 Update pom file to update the lexevs version to 6.5.0.SNAPSHOT.1

- README.md
- pom.xml
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/LexBigServiceFactory.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/bulk/codesystemversion/SearchExtensionBulkDownloader.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/bulk/mapversion/MappingExtensionBulkDownloader.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/LexEvsEntityQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/mapentry/LexEvsMapEntryReadService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/resolvedvalueset/LexEvsResolvedValueSetResolutionService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/valuesetdefinition/LexEvsValueSetDefinitionResolutionService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/utility/CommonUtils.java
- src/main/resources/OSGI-INF/metatype/metatype.xml
- src/test/resources/lexevs-service.properties
Bugfix/lexevscts2 149 Merging dev (1.6.0) to master.
> Bugfix/lexevscts2 149 Merging dev (1.6.0) to master.

- pom.xml
LEXEVSCTS2-152 Updated pom to point to CTS2 1.3.0.FINAL, lexevs 6.5.0.RC1 and updated this version to 1.6.0.RC.1
> LEXEVSCTS2-152 Updated pom to point to CTS2 1.3.0.FINAL, lexevs 6.5.0.RC1 and updated this version to 1.6.0.RC.1

- pom.xml
Bugfix/lexevscts2 157 Merge v1.6.0 branch to master for lexevs 6.5.0 release
> Bugfix/lexevscts2 157 Merge v1.6.0 branch to master for lexevs 6.5.0 release

- pom.xml
Bugfix/lexevscts2 168 Merge v1.6.0 to dev
> Bugfix/lexevscts2 168 Merge v1.6.0 to dev

- pom.xml
LEXEVSCTS2-174 - Updated CTS2 Framework version to 1.3.1.FINAL and version of the Lexevs-service to 1.6.0.RC.3
> LEXEVSCTS2-174 - Updated CTS2 Framework version to 1.3.1.FINAL and version of the Lexevs-service to 1.6.0.RC.3

- pom.xml
LEXEVSCTS2-170 - Updated version to 1.6.0.FINAL.
> LEXEVSCTS2-170 - Updated version to 1.6.0.FINAL.

- README.md
- pom.xml
Bugfix/lexevscts2 182 Merging v1.6.0 branch to dev branch.
This updates the dev branch with the latest 1.6.0.FINAL changes.
> Bugfix/lexevscts2 182 Merging v1.6.0 branch to dev branch.

- README.md
- pom.xml
Bugfix/lexevscts2 182 Merging v1.6.0 branch to master branch.
This updates the master branch with the latest 1.6.0.FINAL changes.
> Bugfix/lexevscts2 182 Merging v1.6.0 branch to master branch.

- pom.xml
LEXEVSCTS2-191 Update Apache Commons from 3.2.1 to 3.2.2
> LEXEVSCTS2-191 Update Apache Commons from 3.2.1 to 3.2.2

- pom.xml
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/LexEVSValueSetDefinitionServicesFactory.java
Bugfix/lexevscts2-164 Remove references to remote API and other other unused code in the POM and code
> Bugfix/lexevscts2-164 Remove references to remote API and other other unused code

- pom.xml
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/resolvedvalueset/LexEVSResolvedValuesetQueryServiceTestIT.java
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/resolvedvalueset/LexEVSResolvedValuesetResolutionServiceTestIT.java
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/valuesetdefinition/ZLexEVSValueSetDefinitionResolutionServiceTestIT.java
- src/test/java/edu/mayo/cts2/framework/plugins/service/LexBigServiceStub.java
- src/test/resources/lexevs/test-content/valueset/ResolvedAllDomesticAutosAndGM.xml
- src/test/resources/lexevs/test-content/valueset/ResolvedAllDomesticAutosAndGMTooLong.xml
- src/test/resources/lexevs/test-content/valueset/ResolvedAllDomesticAutosButGM.xml
Bugfix/lexevscts2-205 Update lexevs-service with latest 6.5.1 jar and fix existing loader issues
> Bugfix/lexevscts2-205 Update lexevs-service with latest 6.5.1 jar and fix existing loader issues

- pom.xml
LEXEVSCTS2-212 Updated lexevs version to 6.5.1.SNAPSHOT.6
> LEXEVSCTS2-212 Updated lexevs version to 6.5.1.SNAPSHOT.6

- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/codesystemversion/LexEvsCodeSystemVersionQueryServiceTestIT.java
- src/test/resources/lexevs/test-content/owl2/owl2-special-cases-Defined-Annotated.owl
LEXEVSCTS2-224 - loading owl2 and adding tests to verify it loaded successfully.
> LEXEVSCTS2-224 - loading owl2 and adding tests to verify it loaded

- pom.xml
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/codesystemversion/LexEvsCodeSystemVersionQueryServiceTestIT.java
Bugfix/lexevscts2 216 - Added Asserted Value Set Index Load tests to CTS2
> Bugfix/lexevscts2 216 - Added Asserted Value Set Index Load tests to CTS2

- pom.xml
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/resolvedvalueset/LexEVSResolvedValuesetQueryServiceTestIT.java
Bugfix/lexevscts2 236 Updated CTS2 version to 1.3.6.RC1, lexevs version to 6.5.1.SNAPSHOT.8
> Bugfix/lexevscts2 236 Updated CTS2 version to 1.3.6.RC1, lexevs version to 6.5.1.SNAPSHOT.8

- pom.xml
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/LexEVSResolvedValueSetServiceFactory.java
Bugfix/lexevscts2 242 - Query Asserted Value Sets based on coding scheme tag.
> Bugfix/lexevscts2 242 - Query Asserted Value Sets based on coding scheme tag.

- pom.xml
LEXEVSCTS2-257 Updated pom file to point to SNAPSHOT.15
> LEXEVSCTS2-257 Updated pom file to point to SNAPSHOT.15

- pom.xml
LEXEVSCTS2-264 Updated pom file to point to SNAPSHOT.16.
> LEXEVSCTS2-264 Updated pom file to point to SNAPSHOT.16.

- pom.xml
LEXEVSCTS2-258 - Update Version to 1.6.1.RC.1
> LEXEVSCTS2-258 - Update Version to 1.6.1.RC.1

- pom.xml
LEXEVSCTS2-201 Update Pom file to reflect the FINAL versions
> LEXEVSCTS2-201 Update Pom file to reflect the FINAL versions

- pom.xml
LEXEVSCTS2-305 - update maven-surefire-plugin version.
> LEXEVSCTS2-305 - update maven-surefire-plugin version.

- pom.xml
LEXEVSCTS2-305 Updated maven-surefire-plugin to fix build.
> LEXEVSCTS2-305 Updated maven-surefire-plugin to fix build.

- pom.xml
Bugfix/lexevscts2 301 Upgraded httpcomponents versions
> Bugfix/lexevscts2 301 Upgraded httpcomponents versions

- pom.xml
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/LexEvsEntityQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/resolvedvalueset/LexEvsResolvedValueSetResolutionService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/utility/CommonPageUtils.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/utility/CommonResourceUtils.java
LEXEVSCTS2-318 - Getting asserted value sets as part of resolved VS.
> LEXEVSCTS2-318 - Getting asserted value sets as part of resolved VS.

- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/utility/MappingExtensionImpl.java
Bugfix/lexevscts2 322 - Merging dev to 1.6.2
> Bugfix/lexevscts2 322 - Merging dev to 1.6.2

- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/resolvedvalueset/LexEvsResolvedValueSetResolutionService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/utility/CommonResourceUtils.java
LEXEVSCTS2-337 - Updated calls to retrieve asserted resolved vs by their description.
> LEXEVSCTS2-337 - Updated calls to retrieve asserted resolved vs by their description.

- pom.xml
LEXEVSCTS2-341 - Updated version to 6.5.2.RC.5
> LEXEVSCTS2-341 - Updated version to 6.5.2.RC.5

- src/test/java/edu/mayo/cts2/framework/plugins/service/LexBigServiceStub.java
LEXEVSCTS2-348 Add lexevs API stub for retrieving the version.
> LEXEVSCTS2-348 Add lexevs API stub for retrieving the version.

- pom.xml
LEXEVSCTS2-352 Updated version to 1.6.2.RC.6 and 6.5.2.RC.6
> LEXEVSCTS2-352 Updated version to 1.6.2.RC.6 and 6.5.2.RC.6

- pom.xml
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/AbstractLexEvsService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/association/LexEvsAssociationQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/codesystemversion/LexEvsCodeSystemVersionQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/DelegatingEntityQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/LexEvsAssociationEntityQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/LexEvsEntityQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/entity/SearchExtensionEntityQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/map/LexEvsMapQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/mapentry/LexEvsMapEntryQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/mapversion/LexEvsMapVersionQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/resolvedvalueset/LexEvsResolvedValueSetResolutionService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/valueset/LexEVSValueSetQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/valuesetdefinition/LexEvsValueSetDefinitionQueryService.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/utility/CommonPageUtils.java
- src/main/java/edu/mayo/cts2/framework/plugin/service/lexevs/utility/CommonResourceUtils.java
LEXEVSCTS2-359 Added method getResourceSummaries() with uri parameter.
> LEXEVSCTS2-359 Added method getResourceSummaries() with uri parameter.

- pom.xml
LEXEVSCTS2-381 Update lexevs version to pull in.
> LEXEVSCTS2-381 Update lexevs version to pull in.

- pom.xml
LEXEVSCTS2-385 updated pom version to 1.6.3.RC.3 and lexevs 6.5.3.RC.3
> LEXEVSCTS2-385 updated pom version to 1.6.3.RC.3 and lexevs 6.5.3.RC.3

- pom.xml
LEXEVSCTS2-392 Updated pom file for 6.5.3.FINAL version.
> LEXEVSCTS2-392 Updated pom file for 6.5.3.FINAL version.

- pom.xml
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/security/msso/RestMssoUserValidatorTest.java
- src/test/java/edu/mayo/cts2/framework/plugin/service/lexevs/service/mapversion/LexEvsMapVersionQueryServiceTestIT.java
LEXEVSCTS2-404 Updated pom, removed felix bundling, updated tests.
> LEXEVSCTS2-404 Updated pom, removed felix bundling, updated tests.

- pom.xml
Bugfix/lexevscts2 420 - update cts2 version to 1.3.9.FINAL
> Bugfix/lexevscts2 420 - update cts2 version to 1.3.9.FINAL
